### ISSUE TITLE
Issue when I run with python 2

### ISSUE THREAD

**Issue by georgethomas08** [pymodbus-dev/pymodbus#1342]
Hi, 

I'm trying to poll the data from a modbus meter, it is working fine with python 3.8< but I have an embedded linux gateway which has only python2.7, I have downgraded the library version to 2.5.3 and installed pip2. still I could get error cleared 

please find the program below

**********************************************************************************************************************************************************

from pymodbus.client.sync import ModbusSerialClient as ModbusClient

UNIT = 0x0A

client = ModbusClient(method='rtu', port='/dev/ttyUSB0')

client.connect()

rr = client.read_input_registers(0, 114, unit=UNIT)
data = rr.registers

print(data)
print()

client.close()

*******************************************************************************************************************************************************

ERROR 
Traceback (most recent call last):
  File "modbus_read3.py", line 34, in <module>
    data = rr.registers
AttributeError: 'ModbusIOException' object has no attribute 'registers'

**Comment by janiversen** [comment]
The error is because your device tells something is wrong, you need to run it again and make a debug log in order to see what happens.

Your program looks fine.

**Comment by janiversen** [comment]
Please remember to downgrade pyserial as well.

**Comment by dhoomakethu** [comment]
Check if you are not getting a error response with `rr.isError()` and then try to read registers.
```
if not rr.isError():
     data = rr.registers
```

**Comment by janiversen** [comment]
Closing as a non-issue.
