### PR TITLE
Fix simulator aiohttp < 3.9.0

### LINKED ISSUE #2287: simulator fails with aiohttp < 3.9
```
=========================== short test summary info ============================
FAILED test/sub_examples/test_examples.py::TestExamples::test_simulator - AttributeError: module 'aiohttp.web' has no attribute 'AppKey'
ERROR test/sub_server/test_simulator.py::TestSimulator::test_simulator_server_tcp - AttributeError: module 'aiohttp.web' has no attribute 'AppKey'
ERROR test/sub_server/test_simulator.py::TestSimulator::test_simulator_server_end_to_end - AttributeError: module 'aiohttp.web' has no attribute 'AppKey'
ERROR test/sub_server/test_simulator.py::TestSimulator::test_simulator_server_string - AttributeError: module 'aiohttp.web' has no attribute 'AppKey'
============ 1 failed, 1013 passed, 12 skipped, 3 errors in 39.91s =============
alex@antorak:~/git/pymodbus$ python3 -m pip list | grep aiohttp
aiohttp                            3.8.6
alex@antorak:~/git/pymodbus$ python3 --version
Python 3.10.12
```

```
< pyproject.toml >
simulator = [
    "aiohttp>=3.8.6;python_version<'3.12'",
    "aiohttp>=3.9.5;python_version=='3.12'"
]
```

Presumably some of the new simulator changes were done with `aiohttp==3.9.x`.  Either they need to be made to work with `3.8.x` or the required version must be bumped.

### PR DESCRIPTION
**Pull request by alexrudd2**
Closes #2287

### CODE REVIEW

**Review by janiversen — COMMENTED** [review]
Good catch! thanks
