### ISSUE TITLE
simulator fails with aiohttp < 3.9

### ISSUE THREAD

**Issue by alexrudd2** [pymodbus-dev/pymodbus#2287]
```
=========================== short test summary info ============================
FAILED test/sub_examples/test_examples.py::TestExamples::test_simulator - AttributeError: module 'aiohttp.web' has no attribute 'AppKey'
ERROR test/sub_server/test_simulator.py::TestSimulator::test_simulator_server_tcp - AttributeError: module 'aiohttp.web' has no attribute 'AppKey'
ERROR test/sub_server/test_simulator.py::TestSimulator::test_simulator_server_end_to_end - AttributeError: module 'aiohttp.web' has no attribute 'AppKey'
ERROR test/sub_server/test_simulator.py::TestSimulator::test_simulator_server_string - AttributeError: module 'aiohttp.web' has no attribute 'AppKey'
============ 1 failed, 1013 passed, 12 skipped, 3 errors in 39.91s =============
alex@antorak:~/git/pymodbus$ python3 -m pip list | grep aiohttp
aiohttp                            3.8.6
alex@antorak:~/git/pymodbus$ python3 --version
Python 3.10.12
```

```
< pyproject.toml >
simulator = [
    "aiohttp>=3.8.6;python_version<'3.12'",
    "aiohttp>=3.9.5;python_version=='3.12'"
]
```

Presumably some of the new simulator changes were done with `aiohttp==3.9.x`.  Either they need to be made to work with `3.8.x` or the required version must be bumped.

**Comment by alexrudd2** [comment]
https://docs.aiohttp.org/en/stable/changes.html#id33

https://github.com/pymodbus-dev/pymodbus/pull/1994/files#diff-7f6e825bb03e0a3b532d82272068a39398ce0fbb9f8d23d5244c48fb78fbe270R210
